
enum class Operation {
  Op_Unknown,
  Op_ADC,
  Op_AND,
  Op_ASL,
  Op_BBR,
  Op_BBS,
  Op_BCC,
  Op_BCS,
  Op_BEQ,
  Op_BIT,
  Op_BMI,
  Op_BNE,
  Op_BPL,
  Op_BRA,
  Op_BRK,
  Op_BVC,
  Op_BVS,
  Op_CLC,
  Op_CLD,
  Op_CLI,
  Op_CLV,
  Op_CMP,
  Op_CPX,
  Op_CPY,
  Op_DEC,
  Op_DEX,
  Op_DEY,
  Op_EOR,
  Op_INC,
  Op_INX,
  Op_INY,
  Op_JMP,
  Op_JSR,
  Op_LDA,
  Op_LDX,
  Op_LDY,
  Op_LSR,
  Op_NOP,
  Op_ORA,
  Op_PHA,
  Op_PHP,
  Op_PHX,
  Op_PHY,
  Op_PLA,
  Op_PLP,
  Op_PLX,
  Op_PLY,
  Op_RMB,
  Op_ROL,
  Op_ROR,
  Op_RTI,
  Op_RTS,
  Op_SBC,
  Op_SEC,
  Op_SED,
  Op_SEI,
  Op_SMB,
  Op_STA,
  Op_STP,
  Op_STX,
  Op_STY,
  Op_STZ,
  Op_TAX,
  Op_TAY,
  Op_TRB,
  Op_TSB,
  Op_TSX,
  Op_TXA,
  Op_TXS,
  Op_TYA,
  Op_WAI
};

const char *OperationNames[] = {
  "???",
  "ADC",
  "AND",
  "ASL",
  "BBR",
  "BBS",
  "BCC",
  "BCS",
  "BEQ",
  "BIT",
  "BMI",
  "BNE",
  "BPL",
  "BRA",
  "BRK",
  "BVC",
  "BVS",
  "CLC",
  "CLD",
  "CLI",
  "CLV",
  "CMP",
  "CPX",
  "CPY",
  "DEC",
  "DEX",
  "DEY",
  "EOR",
  "INC",
  "INX",
  "INY",
  "JMP",
  "JSR",
  "LDA",
  "LDX",
  "LDY",
  "LSR",
  "NOP",
  "ORA",
  "PHA",
  "PHP",
  "PHX",
  "PHY",
  "PLA",
  "PLP",
  "PLX",
  "PLY",
  "RMB",
  "ROL",
  "ROR",
  "RTI",
  "RTS",
  "SBC",
  "SEC",
  "SED",
  "SEI",
  "SMB",
  "STA",
  "STP",
  "STX",
  "STY",
  "STZ",
  "TAX",
  "TAY",
  "TRB",
  "TSB",
  "TSX",
  "TXA",
  "TXS",
  "TYA",
  "WAI",
};

enum class AddressingMode {
  Unknown, Abs, Abs_x_ind, Abs_x, Abs_y, Abs_ind, Accumulator, Immediate, Implied, Pc_rel, Stack, Zp, Zp_x_ind, Zp_x, Zp_y, Zp_ind, Zp_ind_y
};

const char *AddressingModeNames[] = {
  "", " abs", " (abs,x)", " abs,x", " abs,y", " (abs)", " A", " #Immediate", "", " pc+rel", " stack", " zp", " (zp,x)", " zp,x", " zp,y", " (zp)", " (zp),y"
};

const struct { Operation op; AddressingMode mode; } opcodes[] = {
  {Operation::Op_BRK, AddressingMode::Stack},           // 00
  {Operation::Op_ORA, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_TSB, AddressingMode::Zp},
  {Operation::Op_ORA, AddressingMode::Zp},
  {Operation::Op_ASL, AddressingMode::Zp},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_PHP, AddressingMode::Stack},
  {Operation::Op_ORA, AddressingMode::Immediate},
  {Operation::Op_ASL, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_TSB, AddressingMode::Abs},
  {Operation::Op_ORA, AddressingMode::Abs},
  {Operation::Op_ASL, AddressingMode::Abs},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_BPL, AddressingMode::Pc_rel},          // 10
  {Operation::Op_ORA, AddressingMode::Zp_ind_y},
  {Operation::Op_ORA, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_TRB, AddressingMode::Zp},
  {Operation::Op_ORA, AddressingMode::Zp_x},
  {Operation::Op_ASL, AddressingMode::Zp_x},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_CLC, AddressingMode::Implied},
  {Operation::Op_ORA, AddressingMode::Abs_y},
  {Operation::Op_INC, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_TRB, AddressingMode::Abs},
  {Operation::Op_ORA, AddressingMode::Abs_x},
  {Operation::Op_ASL, AddressingMode::Abs_x},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_JSR, AddressingMode::Abs},             // 20
  {Operation::Op_AND, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_BIT, AddressingMode::Zp},
  {Operation::Op_AND, AddressingMode::Zp},
  {Operation::Op_ROL, AddressingMode::Zp},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_PLP, AddressingMode::Stack},
  {Operation::Op_AND, AddressingMode::Immediate},
  {Operation::Op_ROL, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_BIT, AddressingMode::Abs},
  {Operation::Op_AND, AddressingMode::Abs},
  {Operation::Op_ROL, AddressingMode::Abs},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_BMI, AddressingMode::Pc_rel},             // 30
  {Operation::Op_AND, AddressingMode::Zp_ind_y},
  {Operation::Op_AND, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_BIT, AddressingMode::Zp_x},
  {Operation::Op_AND, AddressingMode::Zp_x},
  {Operation::Op_ROL, AddressingMode::Zp_x},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_SEC, AddressingMode::Implied},
  {Operation::Op_AND, AddressingMode::Abs_y},
  {Operation::Op_DEC, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_BIT, AddressingMode::Abs_x},
  {Operation::Op_AND, AddressingMode::Abs_x},
  {Operation::Op_ROL, AddressingMode::Abs_x},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_RTI, AddressingMode::Stack},           // 40
  {Operation::Op_EOR, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_EOR, AddressingMode::Zp},
  {Operation::Op_LSR, AddressingMode::Zp},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_PHA, AddressingMode::Stack},
  {Operation::Op_EOR, AddressingMode::Immediate},
  {Operation::Op_LSR, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_JMP, AddressingMode::Abs},
  {Operation::Op_EOR, AddressingMode::Abs},
  {Operation::Op_LSR, AddressingMode::Abs},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_BVC, AddressingMode::Pc_rel},          // 50
  {Operation::Op_EOR, AddressingMode::Zp_ind_y},
  {Operation::Op_EOR, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_EOR, AddressingMode::Zp_x},
  {Operation::Op_LSR, AddressingMode::Zp_x},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_CLI, AddressingMode::Implied},
  {Operation::Op_EOR, AddressingMode::Abs_y},
  {Operation::Op_PHY, AddressingMode::Stack},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_EOR, AddressingMode::Abs_x},
  {Operation::Op_LSR, AddressingMode::Abs_x},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_RTS, AddressingMode::Stack},           // 60
  {Operation::Op_ADC, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_STZ, AddressingMode::Zp},
  {Operation::Op_ADC, AddressingMode::Zp},
  {Operation::Op_ROR, AddressingMode::Zp},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_PLA, AddressingMode::Stack},
  {Operation::Op_ADC, AddressingMode::Immediate},
  {Operation::Op_ROR, AddressingMode::Accumulator},
  {Operation::Op_Unknown},
  {Operation::Op_JMP, AddressingMode::Abs_ind},
  {Operation::Op_ADC, AddressingMode::Abs},
  {Operation::Op_ROR, AddressingMode::Abs},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_BVS, AddressingMode::Pc_rel},          // 70
  {Operation::Op_ADC, AddressingMode::Zp_ind_y},
  {Operation::Op_ADC, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_STZ, AddressingMode::Zp_x},
  {Operation::Op_ADC, AddressingMode::Zp_x},
  {Operation::Op_ROR, AddressingMode::Zp_x},
  {Operation::Op_RMB, AddressingMode::Zp},
  {Operation::Op_SEI, AddressingMode::Implied},
  {Operation::Op_ADC, AddressingMode::Abs_y},
  {Operation::Op_PLY, AddressingMode::Stack},
  {Operation::Op_Unknown},
  {Operation::Op_JMP, AddressingMode::Abs_x_ind},
  {Operation::Op_ADC, AddressingMode::Abs_x},
  {Operation::Op_ROR, AddressingMode::Abs_x},
  {Operation::Op_BBR, AddressingMode::Pc_rel},
  {Operation::Op_BRA, AddressingMode::Pc_rel},          // 80
  {Operation::Op_STA, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_STY, AddressingMode::Zp},
  {Operation::Op_STA, AddressingMode::Zp},
  {Operation::Op_STX, AddressingMode::Zp},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_DEY, AddressingMode::Implied},
  {Operation::Op_BIT, AddressingMode::Immediate},
  {Operation::Op_TXA, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_STY, AddressingMode::Abs},
  {Operation::Op_STA, AddressingMode::Abs},
  {Operation::Op_STX, AddressingMode::Abs},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_BCC, AddressingMode::Pc_rel},          // 90
  {Operation::Op_STA, AddressingMode::Zp_ind_y},
  {Operation::Op_STA, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_STY, AddressingMode::Zp_x},
  {Operation::Op_STA, AddressingMode::Zp_x},
  {Operation::Op_STX, AddressingMode::Zp_y},
  {Operation::Op_SMB, AddressingMode::Pc_rel},
  {Operation::Op_TYA, AddressingMode::Implied},
  {Operation::Op_STA, AddressingMode::Abs_y},
  {Operation::Op_TXS, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_STZ, AddressingMode::Abs},
  {Operation::Op_STA, AddressingMode::Abs_x},
  {Operation::Op_STZ, AddressingMode::Abs_x},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_LDY, AddressingMode::Immediate},       // a0
  {Operation::Op_LDA, AddressingMode::Zp_x_ind},
  {Operation::Op_LDX, AddressingMode::Immediate},
  {Operation::Op_Unknown},
  {Operation::Op_LDY, AddressingMode::Zp},
  {Operation::Op_LDA, AddressingMode::Zp},
  {Operation::Op_LDX, AddressingMode::Zp},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_TAY, AddressingMode::Implied},
  {Operation::Op_LDA, AddressingMode::Immediate},
  {Operation::Op_TAX, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_LDY, AddressingMode::Abs},
  {Operation::Op_LDA, AddressingMode::Abs},
  {Operation::Op_LDX, AddressingMode::Abs},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_BCS, AddressingMode::Pc_rel},          // b0
  {Operation::Op_LDA, AddressingMode::Zp_ind_y},
  {Operation::Op_LDA, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_LDY, AddressingMode::Zp_x},
  {Operation::Op_LDA, AddressingMode::Zp_x},
  {Operation::Op_LDX, AddressingMode::Zp_y},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_CLV, AddressingMode::Implied},
  {Operation::Op_LDA, AddressingMode::Abs_y},
  {Operation::Op_TSX, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_LDY, AddressingMode::Abs_x},
  {Operation::Op_LDA, AddressingMode::Abs_x},
  {Operation::Op_LDX, AddressingMode::Abs_y},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_CPY, AddressingMode::Immediate},       // c0
  {Operation::Op_CMP, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_CPY, AddressingMode::Zp},
  {Operation::Op_CMP, AddressingMode::Zp},
  {Operation::Op_DEC, AddressingMode::Zp},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_INY, AddressingMode::Implied},
  {Operation::Op_CMP, AddressingMode::Immediate},
  {Operation::Op_DEX, AddressingMode::Implied},
  {Operation::Op_WAI, AddressingMode::Implied},
  {Operation::Op_CPY, AddressingMode::Abs},
  {Operation::Op_CMP, AddressingMode::Abs},
  {Operation::Op_DEC, AddressingMode::Abs},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_BNE, AddressingMode::Pc_rel},          // d0
  {Operation::Op_CMP, AddressingMode::Zp_ind_y},
  {Operation::Op_CMP, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_CMP, AddressingMode::Zp_x},
  {Operation::Op_DEC, AddressingMode::Zp_x},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_CLD, AddressingMode::Implied},
  {Operation::Op_CMP, AddressingMode::Abs_y},
  {Operation::Op_PHX, AddressingMode::Stack},
  {Operation::Op_STP, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_CMP, AddressingMode::Abs_x},
  {Operation::Op_DEC, AddressingMode::Abs_x},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_CPX, AddressingMode::Immediate},       // e0
  {Operation::Op_SBC, AddressingMode::Zp_x_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_CPX, AddressingMode::Zp},
  {Operation::Op_SBC, AddressingMode::Zp},
  {Operation::Op_INC, AddressingMode::Zp},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_INX, AddressingMode::Implied},
  {Operation::Op_SBC, AddressingMode::Immediate},
  {Operation::Op_NOP, AddressingMode::Implied},
  {Operation::Op_Unknown},
  {Operation::Op_CPX, AddressingMode::Abs},
  {Operation::Op_SBC, AddressingMode::Abs},
  {Operation::Op_INC, AddressingMode::Abs},
  {Operation::Op_BBS, AddressingMode::Pc_rel},
  {Operation::Op_BEQ, AddressingMode::Pc_rel},          // f0
  {Operation::Op_SBC, AddressingMode::Zp_ind_y},
  {Operation::Op_SBC, AddressingMode::Zp_ind},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_SBC, AddressingMode::Zp_x},
  {Operation::Op_INC, AddressingMode::Zp_x},
  {Operation::Op_SMB, AddressingMode::Zp},
  {Operation::Op_SED, AddressingMode::Implied},
  {Operation::Op_SBC, AddressingMode::Abs_y},
  {Operation::Op_PLX, AddressingMode::Stack},
  {Operation::Op_Unknown},
  {Operation::Op_Unknown},
  {Operation::Op_SBC, AddressingMode::Abs_x},
  {Operation::Op_INC, AddressingMode::Abs_x},
  {Operation::Op_BBS, AddressingMode::Pc_rel}
};
